#!/bin/bash

JAVA_ARGS="-Xmx1024M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M -Dfile.encoding=UTF8 -Djline.terminal=jline.UnixTerminal"

if [ "$OSTYPE" = cygwin ]; then
	stty -icanon min 1 -echo > /dev/null 2>&1
	SCRIPT_DIR=$(cygpath -w "$(dirname "$(readlink -f "$0")")")
else
	SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
fi

java $JAVA_ARGS -jar "$SCRIPT_DIR/sbt-launch.jar" "$@"

if [ "$OSTYPE" = cygwin ]; then
	stty icanon echo > /dev/null 2>&1
fi
